### ISSUE TITLE
Debug broken clj in docker

### ISSUE THREAD

**Issue by devth** [yetibot/yetibot#716]
Any `clj` expression currently crashes Yetibot when it's running inside a Docker container. Logs look like:

```bash
Exception in thread "async-dispatch-2" java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/log/yetibot/yetibot.log" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.File.exists(File.java:814)
        at taoensso.timbre.appenders.3rd_party.rolling$rolling_appender$fn__21949.invoke(rolling.clj:64)
        at taoensso.timbre$_log_BANG_$fn__10064.invoke(timbre.clj:506)
        at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:373)
        at clojure.core$fn__8080.invokeStatic(core.clj:6765)
        at clojure.core$fn__8080.invoke(core.clj:6750)
        at clojure.core.protocols$fn__7860$G__7855__7869.invoke(protocols.clj:175)
        at clojure.core$reduce_kv.invokeStatic(core.clj:6776)
        at clojure.core$reduce_kv.invoke(core.clj:6767)
        at taoensso.timbre$_log_BANG_.invokeStatic(timbre.clj:441)
        at taoensso.timbre$_log_BANG_.invoke(timbre.clj:345)
        at yetibot.core.handler$handle_raw$fn__19256$state_machine__5856__auto____19265$fn__19267$fn__19272.invoke(handler.clj:93)
        at clojure.core$map$fn__5587.invoke(core.clj:2745)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:528)
        at clojure.core$seq__5124.invokeStatic(core.clj:137)
        at clojure.core$dorun.invokeStatic(core.clj:3125)
        at clojure.core$doall.invokeStatic(core.clj:3140)
        at clojure.core$doall.invoke(core.clj:3140)
        at yetibot.core.handler$handle_raw$fn__19256$state_machine__5856__auto____19265$fn__19267.invoke(handler.clj:86)
        at yetibot.core.handler$handle_raw$fn__19256$state_machine__5856__auto____19265.invoke(handler.clj:76)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at yetibot.core.handler$handle_raw$fn__19256.invoke(handler.clj:76)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by devth** [comment]
I *think* what's happening here is java security manager is lazily loaded by clojail the first time `clj` command is invoked. It looks like the security policy is not configured properly inside the Docker container.

**Comment by devth** [comment]
This fixed it for Docker running locally on macOS but it still errors in Linux 😱

**Comment by devth** [comment]
Fixed for Docker on Linux in https://github.com/yetibot/yetibot/commit/9c36f756becd2bebcf6923c4f6fc428e40163f8f 🤔
