### ISSUE TITLE
clj throws an AccessControlException exception and crashes the bot

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#878]
```
java.security.AccessControlException: access denied ("java.net.NetPermission" "getProxySelector")
        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/java.net.ProxySelector.getDefault(ProxySelector.java:96)
```

**Comment by devth** [comment]
Still happening.
